swagger: "2.0"
info:
  title: 后台管理系统
  description: 'documents of server API powered by swagger, you can also generate
    client code by swagger. refer : https://github.com/swagger-api/swagger-codegen'
  version: 1.0.0
  termsOfService: http://www.horizon.ai/
  contact:
    email: ming.zhao@hobot.cc
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v2
paths: {}
