// Code generated by protoc-gen-go. DO NOT EDIT.
// source: debug.proto

/*
Package debug is a generated protocol buffer package.

It is generated from these files:
	debug.proto

It has these top-level messages:
	MDebugTos
	MDebugToc
	MRestartTos
	MBuildTableTos
	MBuildTableToc
	MBuildProjectTos
	MBuildProjectToc
	MBuildMapTos
	MBuildMapToc
	MBuildSceneTos
	MBuildSceneToc
	MBuildProtoTos
	MBuildProtoToc
*/
package debug

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MDebugToc_ENUM int32

const (
	MDebugToc_success MDebugToc_ENUM = 1
	MDebugToc_fail    MDebugToc_ENUM = 2
)

var MDebugToc_ENUM_name = map[int32]string{
	1: "success",
	2: "fail",
}
var MDebugToc_ENUM_value = map[string]int32{
	"success": 1,
	"fail":    2,
}

func (x MDebugToc_ENUM) Enum() *MDebugToc_ENUM {
	p := new(MDebugToc_ENUM)
	*p = x
	return p
}
func (x MDebugToc_ENUM) String() string {
	return proto.EnumName(MDebugToc_ENUM_name, int32(x))
}
func (x *MDebugToc_ENUM) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MDebugToc_ENUM_value, data, "MDebugToc_ENUM")
	if err != nil {
		return err
	}
	*x = MDebugToc_ENUM(value)
	return nil
}
func (MDebugToc_ENUM) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

// debug
type MDebugTos struct {
	Type             *int32  `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	ParamList        []int32 `protobuf:"varint,2,rep,name=param_list,json=paramList" json:"param_list,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MDebugTos) Reset()                    { *m = MDebugTos{} }
func (m *MDebugTos) String() string            { return proto.CompactTextString(m) }
func (*MDebugTos) ProtoMessage()               {}
func (*MDebugTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MDebugTos) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MDebugTos) GetParamList() []int32 {
	if m != nil {
		return m.ParamList
	}
	return nil
}

// debug
type MDebugToc struct {
	Type             *int32          `protobuf:"varint,1,req,name=type" json:"type,omitempty"`
	Result           *MDebugToc_ENUM `protobuf:"varint,2,req,name=result,enum=MDebugToc_ENUM" json:"result,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *MDebugToc) Reset()                    { *m = MDebugToc{} }
func (m *MDebugToc) String() string            { return proto.CompactTextString(m) }
func (*MDebugToc) ProtoMessage()               {}
func (*MDebugToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MDebugToc) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MDebugToc) GetResult() MDebugToc_ENUM {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return MDebugToc_success
}

// 重启
type MRestartTos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MRestartTos) Reset()                    { *m = MRestartTos{} }
func (m *MRestartTos) String() string            { return proto.CompactTextString(m) }
func (*MRestartTos) ProtoMessage()               {}
func (*MRestartTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// 生成数据
type MBuildTableTos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MBuildTableTos) Reset()                    { *m = MBuildTableTos{} }
func (m *MBuildTableTos) String() string            { return proto.CompactTextString(m) }
func (*MBuildTableTos) ProtoMessage()               {}
func (*MBuildTableTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// 生成数据
type MBuildTableToc struct {
	Result           *string `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MBuildTableToc) Reset()                    { *m = MBuildTableToc{} }
func (m *MBuildTableToc) String() string            { return proto.CompactTextString(m) }
func (*MBuildTableToc) ProtoMessage()               {}
func (*MBuildTableToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MBuildTableToc) GetResult() string {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ""
}

// 编译项目
type MBuildProjectTos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MBuildProjectTos) Reset()                    { *m = MBuildProjectTos{} }
func (m *MBuildProjectTos) String() string            { return proto.CompactTextString(m) }
func (*MBuildProjectTos) ProtoMessage()               {}
func (*MBuildProjectTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// 编译项目
type MBuildProjectToc struct {
	Result           *string `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MBuildProjectToc) Reset()                    { *m = MBuildProjectToc{} }
func (m *MBuildProjectToc) String() string            { return proto.CompactTextString(m) }
func (*MBuildProjectToc) ProtoMessage()               {}
func (*MBuildProjectToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MBuildProjectToc) GetResult() string {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ""
}

// 生成地图数据
type MBuildMapTos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MBuildMapTos) Reset()                    { *m = MBuildMapTos{} }
func (m *MBuildMapTos) String() string            { return proto.CompactTextString(m) }
func (*MBuildMapTos) ProtoMessage()               {}
func (*MBuildMapTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// 生成地图数据
type MBuildMapToc struct {
	Result           *string `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MBuildMapToc) Reset()                    { *m = MBuildMapToc{} }
func (m *MBuildMapToc) String() string            { return proto.CompactTextString(m) }
func (*MBuildMapToc) ProtoMessage()               {}
func (*MBuildMapToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MBuildMapToc) GetResult() string {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ""
}

// 生成场景数据
type MBuildSceneTos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MBuildSceneTos) Reset()                    { *m = MBuildSceneTos{} }
func (m *MBuildSceneTos) String() string            { return proto.CompactTextString(m) }
func (*MBuildSceneTos) ProtoMessage()               {}
func (*MBuildSceneTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

// 生成场景数据
type MBuildSceneToc struct {
	Result           *string `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MBuildSceneToc) Reset()                    { *m = MBuildSceneToc{} }
func (m *MBuildSceneToc) String() string            { return proto.CompactTextString(m) }
func (*MBuildSceneToc) ProtoMessage()               {}
func (*MBuildSceneToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MBuildSceneToc) GetResult() string {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ""
}

// 生成协议
type MBuildProtoTos struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *MBuildProtoTos) Reset()                    { *m = MBuildProtoTos{} }
func (m *MBuildProtoTos) String() string            { return proto.CompactTextString(m) }
func (*MBuildProtoTos) ProtoMessage()               {}
func (*MBuildProtoTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

// 生成协议
type MBuildProtoToc struct {
	Result           *string `protobuf:"bytes,1,req,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MBuildProtoToc) Reset()                    { *m = MBuildProtoToc{} }
func (m *MBuildProtoToc) String() string            { return proto.CompactTextString(m) }
func (*MBuildProtoToc) ProtoMessage()               {}
func (*MBuildProtoToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MBuildProtoToc) GetResult() string {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*MDebugTos)(nil), "m_debug_tos")
	proto.RegisterType((*MDebugToc)(nil), "m_debug_toc")
	proto.RegisterType((*MRestartTos)(nil), "m_restart_tos")
	proto.RegisterType((*MBuildTableTos)(nil), "m_build_table_tos")
	proto.RegisterType((*MBuildTableToc)(nil), "m_build_table_toc")
	proto.RegisterType((*MBuildProjectTos)(nil), "m_build_project_tos")
	proto.RegisterType((*MBuildProjectToc)(nil), "m_build_project_toc")
	proto.RegisterType((*MBuildMapTos)(nil), "m_build_map_tos")
	proto.RegisterType((*MBuildMapToc)(nil), "m_build_map_toc")
	proto.RegisterType((*MBuildSceneTos)(nil), "m_build_scene_tos")
	proto.RegisterType((*MBuildSceneToc)(nil), "m_build_scene_toc")
	proto.RegisterType((*MBuildProtoTos)(nil), "m_build_proto_tos")
	proto.RegisterType((*MBuildProtoToc)(nil), "m_build_proto_toc")
	proto.RegisterEnum("MDebugToc_ENUM", MDebugToc_ENUM_name, MDebugToc_ENUM_value)
}

func init() { proto.RegisterFile("debug.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x59, 0xed, 0xd4, 0xbd, 0xa2, 0x5b, 0x33, 0x94, 0x5d, 0x06, 0x23, 0xa7, 0x0e, 0xb1,
	0x07, 0x3f, 0x81, 0x17, 0x6f, 0xea, 0xa1, 0xe0, 0x39, 0xa4, 0x59, 0x94, 0x6a, 0x62, 0x43, 0xde,
	0xeb, 0xc1, 0x6f, 0x2f, 0x8d, 0x76, 0x94, 0xad, 0x85, 0xdd, 0x92, 0x1f, 0xef, 0xff, 0xcb, 0xff,
	0x11, 0x48, 0x76, 0xba, 0x6c, 0x3e, 0x72, 0xe7, 0x6b, 0xaa, 0xf9, 0x23, 0x24, 0x56, 0x04, 0x20,
	0xa8, 0x46, 0xc6, 0x20, 0xa6, 0x1f, 0xa7, 0x57, 0x93, 0x4d, 0x94, 0x4d, 0x8b, 0x70, 0x66, 0x6b,
	0x00, 0x27, 0xbd, 0xb4, 0xc2, 0x54, 0x48, 0xab, 0x68, 0x73, 0x96, 0x4d, 0x8b, 0x59, 0x20, 0xcf,
	0x15, 0x12, 0xff, 0xea, 0x1b, 0xd4, 0xa0, 0x61, 0x0b, 0xe7, 0x5e, 0x63, 0x63, 0xda, 0x74, 0x94,
	0x5d, 0x3f, 0xa4, 0x79, 0x2f, 0x91, 0x3f, 0xbd, 0xbe, 0xbd, 0x14, 0xff, 0x03, 0x7c, 0x0d, 0x71,
	0x7b, 0x67, 0x09, 0x5c, 0x60, 0xa3, 0x94, 0x46, 0x5c, 0x4c, 0xd8, 0x25, 0xc4, 0xef, 0xb2, 0x32,
	0x8b, 0x88, 0xcf, 0xe1, 0xca, 0x0a, 0xaf, 0x91, 0xa4, 0xa7, 0xb6, 0x30, 0x5f, 0x42, 0x6a, 0x45,
	0xd9, 0x54, 0x66, 0x27, 0x48, 0x96, 0x46, 0x07, 0x78, 0x77, 0x0c, 0x15, 0xbb, 0xdd, 0x97, 0x68,
	0xab, 0xcd, 0xf6, 0x2f, 0xde, 0xc0, 0xb2, 0x1b, 0x76, 0xbe, 0xfe, 0xd4, 0xea, 0x4f, 0x7c, 0x3f,
	0x84, 0xc7, 0x2d, 0x29, 0xcc, 0xbb, 0x71, 0x2b, 0x5d, 0x30, 0x6c, 0x0f, 0xd1, 0x78, 0xba, 0xb7,
	0x05, 0x2a, 0xfd, 0x7d, 0xb4, 0x45, 0x07, 0x4f, 0x32, 0x84, 0x8f, 0x3d, 0x34, 0x74, 0x70, 0xd4,
	0xf0, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xe2, 0xf6, 0x06, 0x17, 0x02, 0x00, 0x00,
}
