// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gm.proto

/*
Package gm is a generated protocol buffer package.

It is generated from these files:
	gm.proto

It has these top-level messages:
	MSetDisableTos
	MSetDisableToc
	MSendMailTos
	MSendMailToc
	MSendNoticeTos
	MSendNoticeToc
	MSetAccountTypeTos
	MSetAccountTypeToc
*/
package gm

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MSetDisableToc_ENUM int32

const (
	MSetDisableToc_success MSetDisableToc_ENUM = 1
	MSetDisableToc_fail    MSetDisableToc_ENUM = 2
)

var MSetDisableToc_ENUM_name = map[int32]string{
	1: "success",
	2: "fail",
}
var MSetDisableToc_ENUM_value = map[string]int32{
	"success": 1,
	"fail":    2,
}

func (x MSetDisableToc_ENUM) Enum() *MSetDisableToc_ENUM {
	p := new(MSetDisableToc_ENUM)
	*p = x
	return p
}
func (x MSetDisableToc_ENUM) String() string {
	return proto.EnumName(MSetDisableToc_ENUM_name, int32(x))
}
func (x *MSetDisableToc_ENUM) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MSetDisableToc_ENUM_value, data, "MSetDisableToc_ENUM")
	if err != nil {
		return err
	}
	*x = MSetDisableToc_ENUM(value)
	return nil
}
func (MSetDisableToc_ENUM) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type MSendMailToc_ENUM int32

const (
	MSendMailToc_success MSendMailToc_ENUM = 1
	MSendMailToc_fail    MSendMailToc_ENUM = 2
)

var MSendMailToc_ENUM_name = map[int32]string{
	1: "success",
	2: "fail",
}
var MSendMailToc_ENUM_value = map[string]int32{
	"success": 1,
	"fail":    2,
}

func (x MSendMailToc_ENUM) Enum() *MSendMailToc_ENUM {
	p := new(MSendMailToc_ENUM)
	*p = x
	return p
}
func (x MSendMailToc_ENUM) String() string {
	return proto.EnumName(MSendMailToc_ENUM_name, int32(x))
}
func (x *MSendMailToc_ENUM) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MSendMailToc_ENUM_value, data, "MSendMailToc_ENUM")
	if err != nil {
		return err
	}
	*x = MSendMailToc_ENUM(value)
	return nil
}
func (MSendMailToc_ENUM) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type MSendNoticeToc_ENUM int32

const (
	MSendNoticeToc_success MSendNoticeToc_ENUM = 1
	MSendNoticeToc_fail    MSendNoticeToc_ENUM = 2
)

var MSendNoticeToc_ENUM_name = map[int32]string{
	1: "success",
	2: "fail",
}
var MSendNoticeToc_ENUM_value = map[string]int32{
	"success": 1,
	"fail":    2,
}

func (x MSendNoticeToc_ENUM) Enum() *MSendNoticeToc_ENUM {
	p := new(MSendNoticeToc_ENUM)
	*p = x
	return p
}
func (x MSendNoticeToc_ENUM) String() string {
	return proto.EnumName(MSendNoticeToc_ENUM_name, int32(x))
}
func (x *MSendNoticeToc_ENUM) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MSendNoticeToc_ENUM_value, data, "MSendNoticeToc_ENUM")
	if err != nil {
		return err
	}
	*x = MSendNoticeToc_ENUM(value)
	return nil
}
func (MSendNoticeToc_ENUM) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

type MSetAccountTypeToc_ENUM int32

const (
	MSetAccountTypeToc_success MSetAccountTypeToc_ENUM = 1
	MSetAccountTypeToc_fail    MSetAccountTypeToc_ENUM = 2
)

var MSetAccountTypeToc_ENUM_name = map[int32]string{
	1: "success",
	2: "fail",
}
var MSetAccountTypeToc_ENUM_value = map[string]int32{
	"success": 1,
	"fail":    2,
}

func (x MSetAccountTypeToc_ENUM) Enum() *MSetAccountTypeToc_ENUM {
	p := new(MSetAccountTypeToc_ENUM)
	*p = x
	return p
}
func (x MSetAccountTypeToc_ENUM) String() string {
	return proto.EnumName(MSetAccountTypeToc_ENUM_name, int32(x))
}
func (x *MSetAccountTypeToc_ENUM) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MSetAccountTypeToc_ENUM_value, data, "MSetAccountTypeToc_ENUM")
	if err != nil {
		return err
	}
	*x = MSetAccountTypeToc_ENUM(value)
	return nil
}
func (MSetAccountTypeToc_ENUM) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{7, 0} }

// 设置封禁
type MSetDisableTos struct {
	Token            *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	Type             *int32  `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	PlayerId         *int32  `protobuf:"varint,3,req,name=player_id,json=playerId" json:"player_id,omitempty"`
	Sec              *int32  `protobuf:"varint,4,req,name=sec" json:"sec,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MSetDisableTos) Reset()                    { *m = MSetDisableTos{} }
func (m *MSetDisableTos) String() string            { return proto.CompactTextString(m) }
func (*MSetDisableTos) ProtoMessage()               {}
func (*MSetDisableTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MSetDisableTos) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *MSetDisableTos) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *MSetDisableTos) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *MSetDisableTos) GetSec() int32 {
	if m != nil && m.Sec != nil {
		return *m.Sec
	}
	return 0
}

// 设置封禁
type MSetDisableToc struct {
	Result           *MSetDisableToc_ENUM `protobuf:"varint,1,req,name=result,enum=MSetDisableToc_ENUM" json:"result,omitempty"`
	Type             *int32               `protobuf:"varint,2,req,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *MSetDisableToc) Reset()                    { *m = MSetDisableToc{} }
func (m *MSetDisableToc) String() string            { return proto.CompactTextString(m) }
func (*MSetDisableToc) ProtoMessage()               {}
func (*MSetDisableToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MSetDisableToc) GetResult() MSetDisableToc_ENUM {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return MSetDisableToc_success
}

func (m *MSetDisableToc) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 发送邮件
type MSendMailTos struct {
	Token            *string             `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	Title            *string             `protobuf:"bytes,2,req,name=title" json:"title,omitempty"`
	Content          *string             `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	PropList         []*MSendMailTosProp `protobuf:"bytes,4,rep,name=propList" json:"propList,omitempty"`
	PlayerNameList   *string             `protobuf:"bytes,5,req,name=playerNameList" json:"playerNameList,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *MSendMailTos) Reset()                    { *m = MSendMailTos{} }
func (m *MSendMailTos) String() string            { return proto.CompactTextString(m) }
func (*MSendMailTos) ProtoMessage()               {}
func (*MSendMailTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MSendMailTos) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *MSendMailTos) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *MSendMailTos) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *MSendMailTos) GetPropList() []*MSendMailTosProp {
	if m != nil {
		return m.PropList
	}
	return nil
}

func (m *MSendMailTos) GetPlayerNameList() string {
	if m != nil && m.PlayerNameList != nil {
		return *m.PlayerNameList
	}
	return ""
}

// 物品
type MSendMailTosProp struct {
	PropType         *int32 `protobuf:"varint,1,req,name=propType" json:"propType,omitempty"`
	PropId           *int32 `protobuf:"varint,2,req,name=propId" json:"propId,omitempty"`
	PropNum          *int32 `protobuf:"varint,3,req,name=propNum" json:"propNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MSendMailTosProp) Reset()                    { *m = MSendMailTosProp{} }
func (m *MSendMailTosProp) String() string            { return proto.CompactTextString(m) }
func (*MSendMailTosProp) ProtoMessage()               {}
func (*MSendMailTosProp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *MSendMailTosProp) GetPropType() int32 {
	if m != nil && m.PropType != nil {
		return *m.PropType
	}
	return 0
}

func (m *MSendMailTosProp) GetPropId() int32 {
	if m != nil && m.PropId != nil {
		return *m.PropId
	}
	return 0
}

func (m *MSendMailTosProp) GetPropNum() int32 {
	if m != nil && m.PropNum != nil {
		return *m.PropNum
	}
	return 0
}

// 发送邮件
type MSendMailToc struct {
	Result           *MSendMailToc_ENUM `protobuf:"varint,1,req,name=result,enum=MSendMailToc_ENUM" json:"result,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *MSendMailToc) Reset()                    { *m = MSendMailToc{} }
func (m *MSendMailToc) String() string            { return proto.CompactTextString(m) }
func (*MSendMailToc) ProtoMessage()               {}
func (*MSendMailToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MSendMailToc) GetResult() MSendMailToc_ENUM {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return MSendMailToc_success
}

// 发送公告
type MSendNoticeTos struct {
	Token            *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	Content          *string `protobuf:"bytes,3,req,name=content" json:"content,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MSendNoticeTos) Reset()                    { *m = MSendNoticeTos{} }
func (m *MSendNoticeTos) String() string            { return proto.CompactTextString(m) }
func (*MSendNoticeTos) ProtoMessage()               {}
func (*MSendNoticeTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MSendNoticeTos) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *MSendNoticeTos) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

// 发送公告
type MSendNoticeToc struct {
	Result           *MSendNoticeToc_ENUM `protobuf:"varint,1,req,name=result,enum=MSendNoticeToc_ENUM" json:"result,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *MSendNoticeToc) Reset()                    { *m = MSendNoticeToc{} }
func (m *MSendNoticeToc) String() string            { return proto.CompactTextString(m) }
func (*MSendNoticeToc) ProtoMessage()               {}
func (*MSendNoticeToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MSendNoticeToc) GetResult() MSendNoticeToc_ENUM {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return MSendNoticeToc_success
}

// 设置帐号类型
type MSetAccountTypeTos struct {
	Token            *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	PlayerId         *int32  `protobuf:"varint,2,req,name=player_id,json=playerId" json:"player_id,omitempty"`
	Type             *int32  `protobuf:"varint,3,req,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MSetAccountTypeTos) Reset()                    { *m = MSetAccountTypeTos{} }
func (m *MSetAccountTypeTos) String() string            { return proto.CompactTextString(m) }
func (*MSetAccountTypeTos) ProtoMessage()               {}
func (*MSetAccountTypeTos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MSetAccountTypeTos) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *MSetAccountTypeTos) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *MSetAccountTypeTos) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

// 设置帐号类型
type MSetAccountTypeToc struct {
	Result           *MSetAccountTypeToc_ENUM `protobuf:"varint,1,req,name=result,enum=MSetAccountTypeToc_ENUM" json:"result,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *MSetAccountTypeToc) Reset()                    { *m = MSetAccountTypeToc{} }
func (m *MSetAccountTypeToc) String() string            { return proto.CompactTextString(m) }
func (*MSetAccountTypeToc) ProtoMessage()               {}
func (*MSetAccountTypeToc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MSetAccountTypeToc) GetResult() MSetAccountTypeToc_ENUM {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return MSetAccountTypeToc_success
}

func init() {
	proto.RegisterType((*MSetDisableTos)(nil), "m_set_disable_tos")
	proto.RegisterType((*MSetDisableToc)(nil), "m_set_disable_toc")
	proto.RegisterType((*MSendMailTos)(nil), "m_send_mail_tos")
	proto.RegisterType((*MSendMailTosProp)(nil), "m_send_mail_tos.prop")
	proto.RegisterType((*MSendMailToc)(nil), "m_send_mail_toc")
	proto.RegisterType((*MSendNoticeTos)(nil), "m_send_notice_tos")
	proto.RegisterType((*MSendNoticeToc)(nil), "m_send_notice_toc")
	proto.RegisterType((*MSetAccountTypeTos)(nil), "m_set_account_type_tos")
	proto.RegisterType((*MSetAccountTypeToc)(nil), "m_set_account_type_toc")
	proto.RegisterEnum("MSetDisableToc_ENUM", MSetDisableToc_ENUM_name, MSetDisableToc_ENUM_value)
	proto.RegisterEnum("MSendMailToc_ENUM", MSendMailToc_ENUM_name, MSendMailToc_ENUM_value)
	proto.RegisterEnum("MSendNoticeToc_ENUM", MSendNoticeToc_ENUM_name, MSendNoticeToc_ENUM_value)
	proto.RegisterEnum("MSetAccountTypeToc_ENUM", MSetAccountTypeToc_ENUM_name, MSetAccountTypeToc_ENUM_value)
}

func init() { proto.RegisterFile("gm.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xa5, 0x49, 0xda, 0xa6, 0x53, 0xa8, 0x75, 0xd0, 0x1a, 0xaa, 0x42, 0xc9, 0x41, 0x7a, 0x31,
	0x62, 0xf1, 0x1f, 0x88, 0x87, 0x82, 0xf6, 0x10, 0xea, 0x79, 0x89, 0x9b, 0x55, 0x82, 0x49, 0x36,
	0x64, 0x37, 0x48, 0xff, 0x81, 0x3f, 0x5b, 0x36, 0x9b, 0x8a, 0xdd, 0x7e, 0x48, 0x6f, 0xf3, 0x26,
	0x2f, 0x33, 0xf3, 0xde, 0x3e, 0x70, 0x3f, 0xb2, 0xa0, 0x28, 0xb9, 0xe4, 0x7e, 0x0a, 0xa7, 0x19,
	0x11, 0x4c, 0x92, 0x38, 0x11, 0xd1, 0x5b, 0xca, 0x88, 0xe4, 0x02, 0xcf, 0xa0, 0x2d, 0xf9, 0x27,
	0xcb, 0xbd, 0xd6, 0xc4, 0x9a, 0xf6, 0x42, 0x0d, 0x10, 0xc1, 0x91, 0xab, 0x82, 0x79, 0xd6, 0xc4,
	0x9a, 0xb6, 0xc3, 0xba, 0xc6, 0x4b, 0xe8, 0x15, 0x69, 0xb4, 0x62, 0x25, 0x49, 0x62, 0xcf, 0xae,
	0x3f, 0xb8, 0xba, 0x31, 0x8f, 0x71, 0x08, 0xb6, 0x60, 0xd4, 0x73, 0xea, 0xb6, 0x2a, 0xfd, 0xaf,
	0xed, 0x6d, 0x14, 0xef, 0xa0, 0x53, 0x32, 0x51, 0xa5, 0xb2, 0x5e, 0x37, 0x98, 0x5d, 0x04, 0x5b,
	0x9c, 0xe0, 0x69, 0xf1, 0xfa, 0x12, 0x36, 0xb4, 0x5d, 0x87, 0xf8, 0xd7, 0xe0, 0x28, 0x0e, 0xf6,
	0xa1, 0x2b, 0x2a, 0x4a, 0x99, 0x10, 0xc3, 0x16, 0xba, 0xe0, 0xbc, 0x47, 0x49, 0x3a, 0xb4, 0xfc,
	0x6f, 0x0b, 0x4e, 0xd4, 0xd4, 0x3c, 0x26, 0x59, 0x94, 0xa4, 0x07, 0x54, 0xaa, 0x6e, 0x22, 0x53,
	0x3d, 0x5d, 0x75, 0x15, 0x40, 0x0f, 0xba, 0x94, 0xe7, 0x92, 0xe5, 0xb2, 0x56, 0xd9, 0x0b, 0xd7,
	0x10, 0xef, 0xc1, 0x2d, 0x4a, 0x5e, 0x3c, 0x27, 0x42, 0x7a, 0xce, 0xc4, 0x9e, 0xf6, 0x67, 0xe7,
	0x81, 0xb1, 0x49, 0x59, 0x5d, 0x84, 0xbf, 0x34, 0xbc, 0x81, 0x81, 0xf6, 0x68, 0x11, 0x65, 0xac,
	0xfe, 0xb1, 0x5d, 0xcf, 0x34, 0xba, 0xe3, 0x25, 0x38, 0xea, 0x1f, 0x1c, 0xeb, 0x15, 0x4b, 0xa5,
	0xb9, 0xd5, 0x78, 0xdc, 0x60, 0x1c, 0x41, 0x47, 0xd5, 0xf3, 0xb8, 0x71, 0xa3, 0x41, 0xea, 0x60,
	0x55, 0x2d, 0xaa, 0xac, 0x79, 0x96, 0x35, 0xf4, 0x89, 0xe9, 0x04, 0xc5, 0x5b, 0xe3, 0x05, 0x4c,
	0x05, 0x9b, 0xfe, 0xff, 0xe7, 0xf5, 0xa3, 0x7e, 0xe4, 0x3c, 0x26, 0x39, 0x97, 0x09, 0x3d, 0x14,
	0xa9, 0xbd, 0xb6, 0xfa, 0x74, 0x7b, 0xc8, 0xbe, 0xa4, 0x6c, 0x70, 0x8e, 0xba, 0x94, 0xc0, 0x48,
	0x47, 0x2d, 0xa2, 0x94, 0x57, 0xb9, 0x24, 0x2a, 0x4a, 0x07, 0xce, 0xdd, 0x48, 0xbb, 0x65, 0xa4,
	0x7d, 0x9d, 0x4a, 0xfb, 0x4f, 0x2a, 0xb3, 0x3d, 0x0b, 0x28, 0x3e, 0x18, 0x52, 0xae, 0x82, 0xdd,
	0xc4, 0x63, 0xf4, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xb7, 0xb8, 0x32, 0xd7, 0x03, 0x00,
	0x00,
}
